### PR TITLE
issue #113 switch to area lookup file

### PR DESCRIPTION
**Pull request by drkane**
Pull request related to issue #113 

This change will switch codes for local authorities, combined authorities, regions & countries to use the new [area_all_codes.csv](https://github.com/drkane/geo-lookups/blob/master/area_all_codes.csv) file from drkane/geo-lookups.

This file contains the appropriate fields for each area - so that if given a region code then `rgncd` will be included in the `LocationLookup` field within `additional_data` - at the moment this isn't the case.

### CODE REVIEW

**Comment by michaelwood** [comment]
This looks good, I've done some testing with Garfield Weston Foundation's data. This is the diff of their generated data https://gist.github.com/michaelwood/9a515ff088f15b0299706d9f17e9be3b

The only thing I'm a little confused about is when we're loosing the ewcd and ewnm fields. 

```diff
-      "ewcd": "",
-      "ewnm": "",
```

That might be my local datastore instance not having the data or perhaps this is expected.. 
We don't have any new ladcd entries either if there was an expectation that those would be populated.

**Comment by KDuerden** [comment]
The missing cases of "gbcd": "" or "gbnm" all make sense in the context of the data - because these are either UK-wide geocodes, or Northern Ireland codes, in the latter case. I'm not sure why it isn't mapping to "ewcd" or "ewnm", as I would expect these to show for any grant with English region geocodes.

There isn't any ladcd geocodes in the data you are testing against - it's all higher level areas, so those being missing is also to be expected.

Would it be helpful for me to give you other examples to try for testing with the wider range of geocoding?

**Comment by drkane** [comment]
Thanks Michael. I made a change that leaves out any blank values rather than keeping them as empty strings. I think this is mostly consistent with the previous behaviour - the `rgn` codes didn't have `ladcd` values for example, which is still the case, but as Katherine says there's a slight change here where the `ewcd` is not included in Scotland.

**Comment by michaelwood** [comment]
Thanks @drkane  yep that makes sense

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
