### PR TITLE
ci: Travis -> GitHub Actions

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by odscjames** [comment]
[Switching from Travis to GH Actions](https://trello.com/c/oz6updTN/127-switching-from-travis-to-gh-actions)

**Comment by odscjames** [comment]
I don't know why lint is failing; it's the same version of black on GH Actions and Travis.

Haven't looked yet into why tests are failing - chrome crash, but no idea why?

Need to leave for today, will come back to.

**Comment by odscjames** [comment]
Lint works, just test to go

**Comment by odscjames** [comment]
First of 2 test fails fixed by adding headless option to browser test.

**Comment by odscjames** [comment]
Ready for review! 

There was no way to make /var/run/user/%s/datarun.pid work so I needed to add a config option. django-environ is a package we have used before eg Cove.

**Comment by michaelwood** [comment]
Thanks this looks good. Could you split it into two or three commits please.

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
